replicaCount: 1
image:
  repository: ghcr.io/1k-off/khai-courses/lab-argo
  pullPolicy: IfNotPresent
  tag: 0.0.22
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: false
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  hosts:
    - host: app-example.lab.1node.tech
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: lab-argo-tls
      hosts:
        - app-example.lab.1node.tech
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
